version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gestionale_db
      POSTGRES_USER: gestionale_user
      POSTGRES_PASSWORD: gestionale_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gestionale_user -d gestionale_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gestionale_db
      - DB_USER=gestionale_user
      - DB_PASSWORD=gestionale_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
