# Generated by Django 5.2.4 on 2025-07-26 00:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Contoterzista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Contoterzista',
                'verbose_name_plural': 'Contoterzisti',
            },
        ),
        migrations.CreateModel(
            name='PrincipioAttivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descrizione', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Principio Attivo',
                'verbose_name_plural': 'Principi Attivi',
            },
        ),
        migrations.CreateModel(
            name='Cascina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cascine', to='domenico.cliente')),
                ('contoterzista', models.ForeignKey(blank=True, help_text='Contoterzista responsabile per questa cascina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascine', to='domenico.contoterzista')),
            ],
            options={
                'verbose_name': 'Cascina',
                'verbose_name_plural': 'Cascine',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('unita_misura', models.CharField(default='L', help_text='Es: L, Kg, g, ml', max_length=20)),
                ('principi_attivi', models.ManyToManyField(related_name='prodotti', to='domenico.principioattivo')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie in ettari', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cascina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terreni', to='domenico.cascina')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terreni',
            },
        ),
        migrations.CreateModel(
            name='Trattamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello_applicazione', models.CharField(choices=[('cliente', 'Cliente'), ('cascina', 'Cascina'), ('terreno', 'Terreno')], max_length=10)),
                ('stato', models.CharField(choices=[('programmato', 'Programmato'), ('comunicato', 'Comunicato'), ('in_esecuzione', 'In Esecuzione'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='programmato', max_length=20)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_comunicazione', models.DateTimeField(blank=True, null=True)),
                ('data_esecuzione_prevista', models.DateField(blank=True, null=True)),
                ('data_esecuzione_effettiva', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('cascina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trattamenti', to='domenico.cascina')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trattamenti', to='domenico.cliente')),
                ('terreni', models.ManyToManyField(blank=True, related_name='trattamenti', to='domenico.terreno')),
            ],
            options={
                'verbose_name': 'Trattamento',
                'verbose_name_plural': 'Trattamenti',
                'ordering': ['-data_inserimento'],
            },
        ),
        migrations.CreateModel(
            name='TrattamentoProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domenico.prodotto')),
                ('trattamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domenico.trattamento')),
            ],
            options={
                'verbose_name': 'Prodotto del Trattamento',
                'verbose_name_plural': 'Prodotti del Trattamento',
                'unique_together': {('trattamento', 'prodotto')},
            },
        ),
        migrations.AddField(
            model_name='trattamento',
            name='prodotti',
            field=models.ManyToManyField(through='domenico.TrattamentoProdotto', to='domenico.prodotto'),
        ),
    ]
