# Generated by Django 5.2.4 on 2025-07-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0002_add_contatti_email_quantita_ettaro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascina',
            name='contoterzista',
            field=models.ForeignKey(blank=True, help_text='Contoterzista responsabile per questa cascina (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascine', to='domenico.contoterzista'),
        ),
    ]
