# Generated by Django 5.2.4 on 2025-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0003_alter_cascina_contoterzista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cascina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trattamentoprodotto',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='trattamentoprodotto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contoterzista',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='trattamento',
            name='prodotti',
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='data_esecuzione_effettiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='livello_applicazione',
            field=models.CharField(choices=[('cliente', 'Intera Azienda'), ('cascina', 'Cascina'), ('terreno', 'Terreni Selezionati')], default='cliente', help_text='Specifica il livello di applicazione del trattamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='note',
            field=models.TextField(blank=True, help_text='Note aggiuntive per il trattamento'),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='stato',
            field=models.CharField(choices=[('programmato', 'Programmato'), ('comunicato', 'Comunicato'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='programmato', help_text='Stato attuale del trattamento', max_length=20),
        ),
    ]
