# Generated by Django 5.2.4 on 2025-07-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0004_alter_cascina_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contattoemail',
            options={'verbose_name': 'Contatto Email', 'verbose_name_plural': 'Contatti Email'},
        ),
        migrations.RemoveField(
            model_name='contattoemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contattoemail',
            name='note',
        ),
        migrations.RemoveField(
            model_name='contattoemail',
            name='priorita',
        ),
        migrations.RemoveField(
            model_name='contattoemail',
            name='ruolo',
        ),
        migrations.RemoveField(
            model_name='contattoemail',
            name='telefono',
        ),
    ]
