# Generated by Django 4.2.11 on 2025-07-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0005_alter_contattoemail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contattoemail',
            name='attivo',
        ),
    ]
