# Generated by Django 4.2.11 on 2025-07-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0006_remove_contattoemail_attivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contattoemail',
            name='email',
            field=models.EmailField(default='', help_text='Indirizzo email del contatto', max_length=254),
            preserve_default=False,
        ),
    ]
