# Generated by Django 5.2.4 on 2025-07-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0007_contattoemail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('cliente_created', 'Cliente Creato'), ('cascina_created', 'Cascina Creata'), ('terreno_created', 'Terreno Creato'), ('prodotto_created', 'Prodotto Creato'), ('contoterzista_created', 'Contoterzista Creato'), ('contatto_created', 'Contatto Email Creato'), ('trattamento_created', 'Trattamento Creato'), ('trattamento_updated', 'Trattamento Aggiornato'), ('comunicazione_sent', 'Comunicazione Inviata'), ('user_login', 'Accesso Utente'), ('data_export', 'Esportazione Dati'), ('backup_created', 'Backup Creato')], help_text='Tipo di attività eseguita', max_length=50)),
                ('title', models.CharField(help_text="Titolo breve dell'attività", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Descrizione dettagliata dell'attività")),
                ('related_object_type', models.CharField(blank=True, help_text='Tipo di oggetto coinvolto (Cliente, Terreno, etc.)', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text="ID dell'oggetto coinvolto", null=True)),
                ('related_object_name', models.CharField(blank=True, help_text="Nome dell'oggetto coinvolto", max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text="Dati aggiuntivi dell'attività in formato JSON")),
            ],
            options={
                'verbose_name': 'Log Attività',
                'verbose_name_plural': 'Log Attività',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='domenico_ac_timesta_924c7e_idx'), models.Index(fields=['activity_type'], name='domenico_ac_activit_4b29fb_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='domenico_ac_related_82dc54_idx')],
            },
        ),
    ]
