# Generated by Django 5.2.4 on 2025-08-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0008_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trattamentoprodotto',
            options={'verbose_name': 'Prodotto del Trattamento', 'verbose_name_plural': 'Prodotti del Trattamento'},
        ),
        migrations.AlterUniqueTogether(
            name='trattamentoprodotto',
            unique_together={('trattamento', 'prodotto')},
        ),
    ]
