# Generated by Django 5.2.4 on 2025-08-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0009_alter_trattamentoprodotto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trattamentoprodotto',
            name='quantita_per_ettaro',
        ),
    ]
