# Generated by Django 5.2.4 on 2025-08-01 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0010_remove_trattamentoprodotto_quantita_per_ettaro'),
    ]

    operations = [
        migrations.AddField(
            model_name='trattamentoprodotto',
            name='quantita_per_ettaro',
            field=models.DecimalField(decimal_places=3, default='1', help_text='Quantità per ettaro', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
            preserve_default=False,
        ),
    ]
