# Generated by Django 5.2.4 on 2025-08-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0011_trattamentoprodotto_quantita_per_ettaro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trattamento',
            old_name='data_esecuzione_effettiva',
            new_name='data_esecuzione',
        ),
        migrations.RemoveField(
            model_name='trattamento',
            name='data_esecuzione_prevista',
        ),
    ]
