# Generated by Django 5.2.4 on 2025-08-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domenico', '0012_rename_data_esecuzione_effettiva_trattamento_data_esecuzione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trattamento',
            name='note',
        ),
    ]
