# Generated by Django 5.2.5 on 2025-09-23 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('ticket_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Richiesta Funzionalità'), ('improvement', 'Miglioramento'), ('question', 'Domanda'), ('other', 'Altro')], default='bug', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorità')),
                ('status', models.CharField(choices=[('open', 'Aperto'), ('in_progress', 'In Lavorazione'), ('resolved', 'Risolto'), ('closed', 'Chiuso')], default='open', max_length=20, verbose_name='Stato')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Utente')),
                ('page_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Pagina')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('browser_info', models.JSONField(blank=True, null=True, verbose_name='Info Browser')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Risolto il')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Commento')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Commento Interno')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creato il')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Commento Ticket',
                'verbose_name_plural': 'Commenti Tickets',
                'ordering': ['created_at'],
            },
        ),
    ]
